name: Updated
version: 1.0.0
description: Save / update a timestamp each time the content is updated
url: https://github.com/jrc9designstudio/statamic-updated
developer: JRC9 Design Studio
developer_url: https://jrc9.ca
